name: main
on: [push, pull_request]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.3.0
        bundler-cache: true
    - name: run test
      run: make test
